Tencent/WeKnora

services/docreader/src/parser/docx_parser.py
=> fix: Fix docx parser init failed

.env.example, docker-compose.yml, services/docreader/src/parser/web_parser.py
feat: Added WEB_PROXY environment variable to optimize web content processing
=> feat: Added WEB_PROXY environment variable

services/docreader/src/parser/storage.py
=> fix: strip minio path prefix

.github/workflows/docker-image.yml, README.md, README_EN.md, frontend/Dockerfile
Added multi-architecture image building and service startup instructions, upgraded Node image and package manager
=> feat: Added multi-architecture image building

README.md, README_EN.md, docker-compose.yml, scripts/build_images.sh, scripts/start_all.sh
Remove architecture-related settings and use the latest image tag uniformly
=> chore: Optimize documents

internal/application/repository/knowledge.go, internal/application/service/knowledge.go, internal/handler/knowledgebase.go
Optimize query logic and concurrent processing, improve error handling and annotations
=> chore(clone): Optimize clone knowledge

internal/application/repository/knowledge.go
Modify the knowledge existence check condition so that parse_status is not failed
=> refactor(knowledge.go): Modify the knowledge existence check

README.md
=> Revert "docs: 添加了配套mcp服务器的说明"

frontend/src/views/initialization/InitializationConfig.vue, scripts/start_all.sh
=> fix: Distinguish between Embedding and Chat detection methods

services/docreader/requirements.txt, services/docreader/src/parser/doc_parser.py
paddlepaddle的3.0.0 cpu版本在并发场景随机产生Segmentation Fault
可详见https://github.com/PaddlePaddle/Paddle/issues/73215，更新至3.2.0可解决问题
https://github.com/PaddlePaddle/Paddle/issues/73215
=> fix(docreader): update paddle version

internal/application/repository/knowledge.go, internal/application/service/knowledge.go, internal/types/interfaces/knowledge.go
并发解析文档文档时错误更新parse_status，导致解析流程不停止
新增解析文档日志
=> fix: parsing documents concurrently

internal/application/service/chat_pipline/rewrite.go
改写结果返回空时，确保使用原始query进行请求
Fix:  #254 
1. 
2. 
3. 
Fixes #
=> fix: rewrite query is empty

internal/handler/initialization.go, scripts/build_images.sh
直接返回APIKEY可能会导致秘钥泄漏，暂时隐藏不返回
1. 
2. 
3. 
Fixes #
=> fix(ui): Ignore showing APIKEY for security

frontend/nginx.conf, frontend/package-lock.json, frontend/package.json, frontend/src/components/doc-content.vue, frontend/src/utils/security.ts, frontend/src/views/chat/components/botmsg.vue, frontend/src/views/chat/components/deepThink.vue, frontend/src/views/chat/components/docInfo.vue, internal/application/service/chat_pipline/into_chat_message.go, internal/application/service/knowledge.go, internal/handler/chunk.go, internal/handler/session.go, internal/utils/security.go
修复潜在的xss漏洞问题
1. 
2. 
3. 
Fixes #
=> fix(ui): Fix xss attact

frontend/src/utils/security.ts, frontend/src/views/chat/components/deepThink.vue, internal/utils/security.go
=> fix(ui): fix xss in thinking

frontend/src/components/doc-content.vue
=> feat: 修复下载文件内容错误问题

frontend/package-lock.json, frontend/package.json, frontend/src/api/initialization/index.ts
=> fix(ui): Fix CSP error

frontend/src/api/initialization/index.ts, frontend/src/assets/img/user-green.svg, frontend/src/assets/img/user.svg, frontend/src/components/menu.vue, frontend/src/router/index.ts, frontend/src/views/initialization/InitializationContent.vue, frontend/src/views/settings/SystemSettings.vue, frontend/src/views/tenant/TenantInfo.vue, internal/handler/initialization.go
调整模型设置页面展示
1. 
2. 
3. 
Fixes #
=> chore(ui): Update Setting page

internal/handler/initialization.go
优化测试大模型连通性
- [x 后端 API (Backend API)
1. 
2. 
3. 
Fixes #
=> fix(app): Update App LLM Model Check logic

Makefile, frontend/src/components/menu.vue, frontend/src/router/index.ts, frontend/src/views/auth/Login.vue, frontend/src/views/initialization/InitializationContent.vue, frontend/src/views/platform/index.vue
修复重新登录后的重定向页面
1. 
2. 
3. 
Fixes #
=> fix(frontend): Fix Login Direct Page

.github/workflows/docker-image.yml
=> chore(build): Optimize Docker build configuration and process

.github/workflows/docker-image.yml, docker/Dockerfile.app
=> chore: upspeed build docker

client/knowledge.go
优化client创建url知识重复时报错信息
新增 URL 重复错误类型及 409 冲突处理
=> feat: Added new URL duplication error type and 409 conflict handling
